// Slug mapping for the Cook Standard.
//
// Keyed by the pre-migration positional anchor ID (sec-N-M-K). The migration
// script in this directory reads this map to rewrite headings and refs.
// After migration, this file remains in-tree as the authoritative registry
// of chapter prefixes and their clauses — future renames update it alongside
// the heading markers.

export const SLUG_MAPPING: Record<string, string> = {
  // ── Chapter 0 — Introduction ──────────────────────────────────────────────
  'sec-0':     'intro',
  'sec-0-1':   'intro.purpose',
  'sec-0-2':   'intro.scope',
  'sec-0-3':   'intro.non-scope',
  'sec-0-4':   'intro.normative-informative',
  'sec-0-5':   'intro.version',
  'sec-0-6':   'intro.architecture-relationship',
  'sec-0-7':   'intro.conformance',

  // ── Chapter 1 — Notation and conventions ──────────────────────────────────
  'sec-1':     'notation',
  'sec-1-1':   'notation.keywords',
  'sec-1-2':   'notation.section-numbering',
  'sec-1-3':   'notation.normative-blocks',
  'sec-1-4':   'notation.grammar',
  'sec-1-5':   'notation.grammar-precedence',
  'sec-1-6':   'notation.amendment-markers',
  'sec-1-7':   'notation.stable-anchors',

  // ── Chapter 2 — Lexical structure ─────────────────────────────────────────
  'sec-2':     'lexical',
  'sec-2-1':   'lexical.source-representation',
  'sec-2-2':   'lexical.tokens',
  'sec-2-3':   'lexical.identifiers',
  'sec-2-4':   'lexical.keywords',
  'sec-2-5':   'lexical.strings',
  'sec-2-6':   'lexical.comments',
  'sec-2-7':   'lexical.line-prefixes',
  'sec-2-8':   'lexical.numbers',
  'sec-2-9':   'lexical.brace-blocks',
  'sec-2-10':  'lexical.line-classification',

  // ── Chapter 3 — Syntactic grammar ─────────────────────────────────────────
  'sec-3':     'grammar',
  'sec-3-1':   'grammar.overview',
  'sec-3-2':   'grammar.top-level-ordering',
  'sec-3-3':   'grammar.var-declarations',
  'sec-3-4':   'grammar.use-declarations',
  'sec-3-5':   'grammar.import-declarations',
  'sec-3-6':   'grammar.config-blocks',
  'sec-3-7':   'grammar.recipes',
  'sec-3-8':   'grammar.step-dispatch',

  // ── Chapter 4 — Recipes and step kinds ────────────────────────────────────
  'sec-4':     'recipes',
  'sec-4-1':   'recipes.header-forms',
  'sec-4-2':   'recipes.dep-list',
  'sec-4-3':   'recipes.ingredients',
  'sec-4-4':   'recipes.step-kinds',
  'sec-4-5':   'recipes.cook-single-output',
  'sec-4-6':   'recipes.cook-multi-output',
  'sec-4-7':   'recipes.plate-step',
  'sec-4-8':   'recipes.test-step',
  'sec-4-9':   'recipes.lua-steps',
  'sec-4-10':  'recipes.shell-steps',
  'sec-4-11':  'recipes.module-call-steps',

  // ── Chapter 5 — Cross-recipe references ───────────────────────────────────
  'sec-5':       'xref',
  'sec-5-1':     'xref.name-references',
  'sec-5-2':     'xref.resolution',
  'sec-5-2-1':   'xref.dotted-names',
  'sec-5-2-2':   'xref.reserved-segment',
  'sec-5-2-3':   'xref.env-shadowing',
  'sec-5-3':     'xref.path-accessors',
  'sec-5-4':     'xref.dep-driven',
  'sec-5-4-1':   'xref.dep-recipe-output',
  'sec-5-4-2':   'xref.dep-driven-example',
  'sec-5-5':     'xref.string-substitution',
  'sec-5-5-1':   'xref.string-substitution-example',
  'sec-5-6':     'xref.dep-implications',

  // ── Chapter 6 — Cook Lua API ───────────────────────────────────────────────
  'sec-6':       'lua',
  'sec-6-1':     'lua.api-overview',
  'sec-6-1-1':   'lua.recipe-global',
  'sec-6-2':     'lua.add-unit',
  'sec-6-3':     'lua.step-helpers',
  'sec-6-3-1':   'lua.cook-sh',
  'sec-6-3-2':   'lua.cook-exec',
  'sec-6-3-3':   'lua.cook-recipe',
  'sec-6-4':     'lua.using-block-globals',
  'sec-6-5':     'lua.fs-helpers',
  'sec-6-5-1':   'lua.fs-exists',
  'sec-6-5-2':   'lua.fs-size',
  'sec-6-5-3':   'lua.fs-read',
  'sec-6-5-4':   'lua.fs-write',
  'sec-6-5-5':   'lua.fs-mkdir-p',
  'sec-6-5-6':   'lua.fs-glob',
  'sec-6-5-7':   'lua.fs-mtime',
  'sec-6-6':     'lua.path-helpers',
  'sec-6-6-1':   'lua.path-stem',
  'sec-6-6-2':   'lua.path-name',
  'sec-6-6-3':   'lua.path-ext',
  'sec-6-6-4':   'lua.path-dir',
  'sec-6-6-5':   'lua.path-replace-ext',
  'sec-6-6-6':   'lua.path-join',
  'sec-6-7':     'lua.shell-placeholders',
  'sec-6-8':     'lua.use-declaration',
  'sec-6-8-1':   'lua.builtin-modules',
  'sec-6-8-2':   'lua.local-modules',

  // ── Chapter 7 — Cross-Cookfile composition ────────────────────────────────
  'sec-7':     'modules',
  'sec-7-1':   'modules.overview',
  'sec-7-2':   'modules.import-declaration',
  'sec-7-3':   'modules.qualified-refs',
  'sec-7-4':   'modules.duplicate-cycle-detection',

  // ── Chapter 8 — Execution model ───────────────────────────────────────────
  'sec-8':     'exec',
  'sec-8-1':   'exec.two-phase',
  'sec-8-2':   'exec.capture-mode',
  'sec-8-3':   'exec.step-groups',
  'sec-8-4':   'exec.cross-recipe-ordering',
  'sec-8-5':   'exec.interactive-drain',
  'sec-8-6':   'exec.cache',
  'sec-8-7':   'exec.diagnostic-ordering',

  // ── Appendix A — Grammar (normative) ──────────────────────────────────────
  'sec-A-1':   'grammar-appendix.top-level',
  'sec-A-2':   'grammar-appendix.declarations',
  'sec-A-3':   'grammar-appendix.recipes',
  'sec-A-4':   'grammar-appendix.steps',
  'sec-A-5':   'grammar-appendix.primitives',

  // ── Appendix B — Rationale (informative) ──────────────────────────────────
  'sec-B-0':     'rationale.intro',
  'sec-B-1':     'rationale.notation',
  'sec-B-2':     'rationale.lexical',
  'sec-B-2-2':   'rationale.one-token-per-line',
  'sec-B-2-3':   'rationale.ascii-identifiers',
  'sec-B-2-4':   'rationale.contextual-keywords',
  'sec-B-2-7':   'rationale.at-not-lexical',
  'sec-B-3':     'rationale.grammar',
  'sec-B-3-2':   'rationale.ordered-prefix',
  'sec-B-3-7':   'rationale.implicit-header-col0',
  'sec-B-3-8':   'rationale.name-value-shell',
  'sec-B-4':     'rationale.recipes',
  'sec-B-4-6':   'rationale.multi-output-using-error',
  'sec-B-4-7':   'rationale.plate-single-template',
  'sec-B-4-11':  'rationale.module-call-heuristic',
  'sec-B-5':     'rationale.exec',
  'sec-B-5-1':   'rationale.register-phase-pure',
  'sec-B-5-2':   'rationale.interactive-drain',
  'sec-B-5-3':   'rationale.abstract-cache',
  'sec-B-5-4':   'rationale.diagnostic-ordering',
  'sec-B-6':     'rationale.lua',
  'sec-B-6-1':   'rationale.placeholder-vs-globals',
  'sec-B-6-2':   'rationale.fs-path-namespaces',
  'sec-B-6-3':   'rationale.add-unit-register-only',
  'sec-B-6-4':   'rationale.recipe-name-priority',
  'sec-B-7':     'rationale.modules',
  'sec-B-7-1':   'rationale.duplicate-import-parse-time',
  'sec-B-7-2':   'rationale.cycle-load-time',
  'sec-B-7-3':   'rationale.module-name-no-collision',

  // ── Appendix C — Worked examples (informative) ────────────────────────────
  'sec-C-1':   'examples.multi-output-cook',
  'sec-C-2':   'examples.cross-recipe-dep',
  'sec-C-3':   'examples.module-use-call',
  'sec-C-4':   'examples.lua-multi-output',
  'sec-C-5':   'examples.cross-recipe-refs',
};
