use super::*;

#[test]
fn alias_rewrites_hyphens_only() {
    assert_eq!(alias_of("plain"), "plain");
    assert_eq!(alias_of("my-mod"), "my_mod");
    assert_eq!(alias_of("a-b-c"), "a_b_c");
    assert_eq!(alias_of("keeps_underscores"), "keeps_underscores");
}

#[test]
fn the_call_is_qualified_and_uses_the_installed_field_name() {
    assert!(load_module_call("greet").contains(LOAD_MODULE_FN));
    assert_eq!(load_module_call("greet"), "cook.load_module(\"greet\")");
}

#[test]
fn the_disk_name_is_not_rewritten() {
    // Note 12.1.1: the alias loses the hyphen, the lookup does not.
    assert_eq!(
        binding(&alias_of("my-mod"), "my-mod"),
        "local my_mod = cook.load_module(\"my-mod\")"
    );
}

#[test]
fn the_module_name_is_escaped_for_a_double_quoted_literal() {
    // Not reachable from `use` today, but the composition must not be the
    // place a name with a quote in it becomes a syntax error somewhere else.
    assert_eq!(load_module_call("a\"b"), "cook.load_module(\"a\\\"b\")");
}

#[test]
fn the_binding_carries_no_terminator_or_newline() {
    // Framing belongs to the emitter: `cook-luagen` ends it with a newline in
    // the register chunk, with `; ` in an execute-phase body prelude, and with
    // ` -- Generated by Cook` on the first line of a config-block Cookfile
    // (CS-0126). A terminator baked in here would make one of those wrong.
    let b = binding("greet", "greet");
    assert!(!b.ends_with('\n'));
    assert!(!b.ends_with(';'));
}

// --- CS-0206: the path form -------------------------------------------------

#[test]
fn the_lua_suffix_is_what_separates_the_two_forms() {
    assert!(!is_path_target("greet"));
    assert!(!is_path_target("cook_cc"));
    assert!(is_path_target("build/helpers.lua"));
    assert!(is_path_target("./build/helpers.lua"));
    assert!(is_path_target("helpers.lua"));
}

#[test]
fn a_name_cs0035_rejects_is_still_judged_as_a_name() {
    // The discriminator is deliberately NOT "fails to lex as an identifier".
    // `use my-mod` must keep reaching CS-0035's diagnostic about a malformed
    // NAME rather than being re-read as a path missing a `.lua`.
    assert!(!is_path_target("my-mod"));
    assert!(!is_path_target("cpp.bad"));
    assert!(!is_path_target("9lives"));
}

#[test]
fn the_derived_alias_is_the_basename_stem_through_the_hyphen_rewrite() {
    assert_eq!(derived_alias("build/helpers.lua"), "helpers");
    assert_eq!(derived_alias("./build/helpers.lua"), "helpers");
    assert_eq!(derived_alias("helpers.lua"), "helpers");
    // COOK-436: the rewrite's first reachable input. A basename passes through
    // no name production, so it is under no obligation to be an identifier
    // before the rewrite.
    assert_eq!(derived_alias("build/my-helpers.lua"), "my_helpers");
}

#[test]
fn a_derived_alias_that_is_not_an_identifier_is_returned_not_mangled() {
    // Judging it belongs to the caller that owns the diagnostic (cook-lang),
    // which names the explicit-alias form as the remedy. Silently mangling it
    // here would bind a name the author never wrote.
    assert_eq!(derived_alias("build/9lives.lua"), "9lives");
    assert_eq!(derived_alias("build/my.helpers.lua"), "my.helpers");
}

#[test]
fn a_path_form_binds_through_the_same_door_with_the_path_as_the_target() {
    // §24.2: the path form gets no resolver of its own. A module bound by any
    // route other than LOAD_MODULE_FN leaves CS-0204's determinant set.
    let b = binding("helpers", "build/helpers.lua");
    assert_eq!(b, "local helpers = cook.load_module(\"build/helpers.lua\")");
    assert!(b.contains(LOAD_MODULE_FN));
}

#[test]
fn an_explicit_alias_is_bound_verbatim_not_re_derived() {
    assert_eq!(
        binding("fmt", "tools/lua/code-formatting.lua"),
        "local fmt = cook.load_module(\"tools/lua/code-formatting.lua\")"
    );
}
