use super::*;

#[test]
fn alias_rewrites_hyphens_only() {
    assert_eq!(alias_of("plain"), "plain");
    assert_eq!(alias_of("my-mod"), "my_mod");
    assert_eq!(alias_of("a-b-c"), "a_b_c");
    assert_eq!(alias_of("keeps_underscores"), "keeps_underscores");
}

#[test]
fn the_call_is_qualified_and_uses_the_installed_field_name() {
    assert!(load_module_call("greet").contains(LOAD_MODULE_FN));
    assert_eq!(load_module_call("greet"), "cook.load_module(\"greet\")");
}

#[test]
fn the_disk_name_is_not_rewritten() {
    // Note 12.1.1: the alias loses the hyphen, the lookup does not.
    assert_eq!(
        binding("my-mod"),
        "local my_mod = cook.load_module(\"my-mod\")"
    );
}

#[test]
fn the_module_name_is_escaped_for_a_double_quoted_literal() {
    // Not reachable from `use` today, but the composition must not be the
    // place a name with a quote in it becomes a syntax error somewhere else.
    assert_eq!(load_module_call("a\"b"), "cook.load_module(\"a\\\"b\")");
}

#[test]
fn the_binding_carries_no_terminator_or_newline() {
    // Framing belongs to the emitter: `cook-luagen` ends it with a newline in
    // the register chunk, with `; ` in an execute-phase body prelude, and with
    // ` -- Generated by Cook` on the first line of a config-block Cookfile
    // (CS-0126). A terminator baked in here would make one of those wrong.
    let b = binding("greet");
    assert!(!b.ends_with('\n'));
    assert!(!b.ends_with(';'));
}
