//! M3.2 — `cook.lock` format, integrity verification, closure introspection.
//!
//! `cook.lock` is the deterministic state for `cook modules install`.
//! Generated by every state-changing invocation; consumed by plain
//! `cook modules install` to enforce reproducibility. The closure includes
//! both top-level (`direct = true`) and transitive (`direct = false`) rocks —
//! a full closure, matching Cargo / pnpm / Bundler.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, Context, Result};
use base64::{engine::general_purpose::STANDARD as B64, Engine};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::modules::manifest::ManifestModules;

const SCHEMA_VERSION: u32 = 1;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Lockfile {
    pub schema: u32,
    #[serde(rename = "module", default)]
    pub modules: Vec<LockedModule>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LockedModule {
    pub name: String,
    pub version: String,
    pub source: String,
    pub integrity: String,
    pub direct: bool,
}

impl Lockfile {
    pub fn new(modules: Vec<LockedModule>) -> Self {
        Self {
            schema: SCHEMA_VERSION,
            modules,
        }
    }
}

pub fn read(path: &Path) -> Result<Lockfile> {
    let raw = std::fs::read_to_string(path)
        .with_context(|| format!("read {}", path.display()))?;
    let parsed: Lockfile = toml::from_str(&raw)
        .with_context(|| format!("parse {}", path.display()))?;
    if parsed.schema > SCHEMA_VERSION {
        return Err(anyhow!(
            "cook.lock schema version {} is newer than this cook supports (max {}); upgrade cook",
            parsed.schema,
            SCHEMA_VERSION
        ));
    }
    Ok(parsed)
}

pub fn write(path: &Path, lock: &Lockfile) -> Result<()> {
    let contents = toml::to_string_pretty(lock)
        .with_context(|| "serialize cook.lock")?;
    std::fs::write(path, contents)
        .with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

/// Verify the on-disk source rock matches the integrity in the lockfile.
/// `cache_dir` is `cook_modules/lib/luarocks/cache/` — the directory luarocks
/// caches downloaded source rocks into.
pub fn verify_integrity(locked: &LockedModule, cache_dir: &Path) -> Result<()> {
    let filename = format!("{}-{}.src.rock", locked.name, locked.version);
    let path = cache_dir.join(&filename);
    let bytes = std::fs::read(&path)
        .with_context(|| format!("read {}", path.display()))?;
    let mut h = Sha256::new();
    h.update(&bytes);
    let actual = format!("sha256-{}", B64.encode(h.finalize()));
    if actual != locked.integrity {
        return Err(anyhow!(
            "integrity mismatch for {}-{}: lockfile expects {}, on-disk computes {}",
            locked.name,
            locked.version,
            locked.integrity,
            actual
        ));
    }
    Ok(())
}

/// Walk `cook_modules/lib/luarocks/rocks-5.4/<name>/<version>/` and produce a
/// Lockfile pinning every rock present. `direct = true` for rocks named in the
/// manifest, else `false`.
///
/// Source URLs come from each rock's `<name>-<version>.rockspec` file (the
/// `source.url` field). Integrity hashes come from
/// `cook_modules/lib/luarocks/cache/<name>-<version>.src.rock`.
pub fn introspect_closure(modules_dir: &Path, manifest: &ManifestModules) -> Result<Lockfile> {
    let rocks_root = modules_dir.join("lib/luarocks/rocks-5.4");
    let cache_dir = modules_dir.join("lib/luarocks/cache");
    let mut out = Vec::new();
    if !rocks_root.is_dir() {
        return Ok(Lockfile::new(out));
    }
    let mut by_name: BTreeMap<String, BTreeMap<String, PathBuf>> = BTreeMap::new();
    for name_entry in std::fs::read_dir(&rocks_root)
        .with_context(|| format!("read {}", rocks_root.display()))?
    {
        let name_entry = name_entry?;
        if !name_entry.file_type()?.is_dir() {
            continue;
        }
        let name = name_entry.file_name().to_string_lossy().into_owned();
        for version_entry in std::fs::read_dir(name_entry.path())? {
            let version_entry = version_entry?;
            if !version_entry.file_type()?.is_dir() {
                continue;
            }
            let version = version_entry.file_name().to_string_lossy().into_owned();
            by_name
                .entry(name.clone())
                .or_default()
                .insert(version, version_entry.path());
        }
    }
    for (name, versions) in by_name {
        // Pick the highest version present (luarocks may keep older versions).
        // Sorted lex order is good enough here — semver-precise picking is
        // luarocks's job at install time.
        let (version, dir) = versions.into_iter().next_back().unwrap();
        let rockspec_path = dir.join(format!("{}-{}.rockspec", name, version));
        let source_url = parse_rockspec_source_url(&rockspec_path)
            .with_context(|| format!("read source.url from {}", rockspec_path.display()))?;
        let integrity = compute_integrity(&cache_dir, &name, &version)
            .with_context(|| format!("compute integrity for {}-{}", name, version))?;
        let direct = manifest.modules.contains_key(&name);
        out.push(LockedModule {
            name,
            version,
            source: source_url,
            integrity,
            direct,
        });
    }
    out.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(Lockfile::new(out))
}

fn parse_rockspec_source_url(path: &Path) -> Result<String> {
    let raw = std::fs::read_to_string(path)
        .with_context(|| format!("read {}", path.display()))?;
    // Rockspecs are Lua, not TOML. We do a minimal text scrape for the
    // `source = { url = "..." }` field; full Lua eval would be overkill.
    for line in raw.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("url") {
            let rest = rest.trim_start();
            if let Some(rest) = rest.strip_prefix('=') {
                let rest = rest.trim();
                let rest = rest.trim_start_matches('"').trim_end_matches(',').trim();
                let rest = rest.trim_end_matches('"');
                return Ok(rest.to_string());
            }
        }
    }
    Err(anyhow!(
        "rockspec at {} has no top-level `url = \"...\"` line",
        path.display()
    ))
}

fn compute_integrity(cache_dir: &Path, name: &str, version: &str) -> Result<String> {
    let path = cache_dir.join(format!("{}-{}.src.rock", name, version));
    if !path.exists() {
        // No cached source rock — luarocks installed from a local path or
        // a pre-existing tree. Mark as unknown integrity; the lockfile is
        // honest about gaps.
        return Ok("sha256-unknown".to_string());
    }
    let bytes = std::fs::read(&path)
        .with_context(|| format!("read {}", path.display()))?;
    let mut h = Sha256::new();
    h.update(&bytes);
    Ok(format!("sha256-{}", B64.encode(h.finalize())))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use std::path::PathBuf;

    fn fixture_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/lockfile/rock_tree")
    }

    fn sample_lockfile() -> Lockfile {
        Lockfile::new(vec![
            LockedModule {
                name: "cook_smoke".into(),
                version: "0.1.0-1".into(),
                source: "https://rocks.usecook.com/cook_smoke-0.1.0-1.src.rock".into(),
                integrity: "sha256-1f3d".into(),
                direct: true,
            },
            LockedModule {
                name: "luafilesystem".into(),
                version: "1.8.0-1".into(),
                source: "https://luarocks.org/manifests/hisham/luafilesystem-1.8.0-1.src.rock"
                    .into(),
                integrity: "sha256-9b2c".into(),
                direct: false,
            },
        ])
    }

    #[test]
    fn round_trip_serialization() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("cook.lock");
        let lock = sample_lockfile();
        write(&path, &lock).expect("write");
        let read_back = read(&path).expect("read");
        assert_eq!(read_back, lock);
    }

    #[test]
    fn schema_mismatch_rejected() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("cook.lock");
        let mut f = std::fs::File::create(&path).expect("create");
        writeln!(f, "schema = 99").expect("write");
        let err = read(&path).expect_err("must fail");
        assert!(format!("{:#}", err).contains("schema version 99"));
    }

    #[test]
    fn integrity_match_ok() {
        // Use the fixture cache + a hash matching its on-disk content.
        // Compute the expected hash inline so the test is self-checking.
        let cache = fixture_root().join("lib/luarocks/cache");
        let bytes = std::fs::read(cache.join("cook_smoke-0.1.0-1.src.rock"))
            .expect("read fixture");
        let mut h = Sha256::new();
        h.update(&bytes);
        let expected = format!("sha256-{}", B64.encode(h.finalize()));
        let locked = LockedModule {
            name: "cook_smoke".into(),
            version: "0.1.0-1".into(),
            source: "https://rocks.usecook.com/cook_smoke-0.1.0-1.src.rock".into(),
            integrity: expected,
            direct: true,
        };
        verify_integrity(&locked, &cache).expect("integrity ok");
    }

    #[test]
    fn integrity_mismatch_errors_with_both_hashes() {
        let cache = fixture_root().join("lib/luarocks/cache");
        let locked = LockedModule {
            name: "cook_smoke".into(),
            version: "0.1.0-1".into(),
            source: "https://example/cook_smoke.src.rock".into(),
            integrity: "sha256-wrong".into(),
            direct: true,
        };
        let err = verify_integrity(&locked, &cache).expect_err("must fail");
        let msg = format!("{:#}", err);
        assert!(msg.contains("cook_smoke"));
        assert!(msg.contains("expects"));
        assert!(msg.contains("computes"));
    }

    #[test]
    fn introspect_closure_marks_direct_correctly() {
        let mut manifest = ManifestModules::default();
        manifest.modules.insert("cook_smoke".into(), "*".into());
        // luafilesystem is NOT in the manifest -> direct = false.
        let modules_dir = fixture_root();
        let lock = introspect_closure(&modules_dir, &manifest).expect("introspect");
        assert_eq!(lock.modules.len(), 2);
        let by_name: std::collections::HashMap<&str, &LockedModule> = lock
            .modules
            .iter()
            .map(|m| (m.name.as_str(), m))
            .collect();
        assert!(by_name["cook_smoke"].direct);
        assert!(!by_name["luafilesystem"].direct);
        assert_eq!(by_name["cook_smoke"].version, "0.1.0-1");
        assert_eq!(
            by_name["cook_smoke"].source,
            "https://rocks.usecook.com/cook_smoke-0.1.0-1.src.rock"
        );
    }

    #[test]
    fn introspect_empty_tree_yields_empty_lockfile() {
        let dir = tempfile::tempdir().expect("tempdir");
        let lock = introspect_closure(dir.path(), &ManifestModules::default())
            .expect("introspect");
        assert!(lock.modules.is_empty());
        assert_eq!(lock.schema, SCHEMA_VERSION);
    }
}
