use cook_lang::ast::*;

use crate::cook_step::generate_cook_step;
use crate::lua_string::{escape_lua_string, wrap_lua_string};
use crate::plate_step::generate_plate_step;
use crate::test_step;

pub fn generate(cookfile: &Cookfile) -> String {
    let mut out = String::from("-- Generated by Cook\n");

    // Emit module loading for use statements
    for use_stmt in &cookfile.uses {
        let lua_name = use_stmt.module_name.replace('-', "_");
        out.push_str(&format!(
            "local {} = cook.load_module(\"{}\")\n",
            lua_name,
            escape_lua_string(&use_stmt.module_name),
        ));
    }
    if !cookfile.uses.is_empty() {
        out.push('\n');
    }

    for recipe in &cookfile.recipes {
        out.push_str(&format!(
            "cook.recipe(\"{}\", {}, function()\n",
            escape_lua_string(&recipe.name),
            generate_metadata(recipe)
        ));

        let mut prev_cook_index: Option<usize> = None;
        let mut cook_index: usize = 0;

        for step in &recipe.steps {
            match step {
                Step::Shell { command, line: _, interactive } => {
                    let wrapped = wrap_lua_string(command);
                    if *interactive {
                        out.push_str(&format!(
                            "    cook.add_unit({{command = {}, interactive = true, cache = false}})\n",
                            wrapped
                        ));
                    } else {
                        out.push_str(&format!(
                            "    cook.add_unit({{command = {}, cache = false}})\n",
                            wrapped
                        ));
                    }
                }
                Step::Lua { code, .. } => {
                    out.push_str(&format!("    {}\n", code));
                }
                Step::LuaBlock { code, .. } => {
                    for code_line in code.lines() {
                        out.push_str(&format!("    {}\n", code_line));
                    }
                }
                Step::Cook {
                    step: cook_step,
                    line,
                } => {
                    cook_index += 1;
                    // Hoist output collection variable to recipe scope
                    // so subsequent step_groups can reference it
                    out.push_str(&format!("    local _cook_outputs_{} = {{}}\n", cook_index));
                    out.push_str("    cook.step_group(function()\n");
                    generate_cook_step(
                        &mut out,
                        cook_step,
                        *line,
                        cook_index,
                        prev_cook_index,
                        &recipe.ingredients,
                    );
                    out.push_str("    end)\n");
                    prev_cook_index = Some(cook_index);
                }
                Step::Plate {
                    step: plate_step,
                    line,
                } => {
                    out.push_str("    cook.step_group(function()\n");
                    generate_plate_step(&mut out, plate_step, *line, prev_cook_index);
                    out.push_str("    end)\n");
                }
                Step::Test {
                    step: test_step_val,
                    line,
                } => {
                    out.push_str("    cook.step_group(function()\n");
                    test_step::generate_test_step(&mut out, test_step_val, *line, prev_cook_index);
                    out.push_str("    end)\n");
                }
            }
        }

        out.push_str("end)\n\n");
    }

    out
}

fn generate_metadata(recipe: &Recipe) -> String {
    let mut fields = Vec::new();
    if !recipe.ingredients.is_empty() {
        let items: Vec<String> = recipe
            .ingredients
            .iter()
            .map(|s| format!("\"{}\"", escape_lua_string(s)))
            .collect();
        fields.push(format!("ingredients = {{{}}}", items.join(", ")));
    }
    if !recipe.excludes.is_empty() {
        let items: Vec<String> = recipe
            .excludes
            .iter()
            .map(|s| format!("\"{}\"", escape_lua_string(s)))
            .collect();
        fields.push(format!("excludes = {{{}}}", items.join(", ")));
    }
    if !recipe.deps.is_empty() {
        let items: Vec<String> = recipe
            .deps
            .iter()
            .map(|s| format!("\"{}\"", escape_lua_string(s)))
            .collect();
        fields.push(format!("requires = {{{}}}", items.join(", ")));
    }
    if fields.is_empty() {
        "{}".to_string()
    } else {
        format!("{{{}}}", fields.join(", "))
    }
}
