use std::collections::BTreeSet;

use cook_lang::ast::*;

use crate::cook_step::generate_cook_step;
use crate::dep_ref::extract_dep_refs;
use crate::lua_string::{escape_lua_string, wrap_lua_string};
use crate::plate_step::generate_plate_step;
use crate::test_step;

pub fn generate(cookfile: &Cookfile) -> String {
    generate_with_names(cookfile, &BTreeSet::new())
}

/// Lower `cookfile` and return any register-time warnings alongside the Lua
/// source.
///
/// Current warnings:
/// - **Empty-output reference (Cook Standard § 5.5).** When a `{NAME}` or
///   `{NAME.ACCESSOR}` reference names a recipe whose output list at register
///   time is empty (i.e. has no cook steps and no ingredients), we emit a
///   warning naming both the referrer and referent. The reference itself is
///   still lowered — the substitution is the empty string — so callers must
///   not treat this as an error.
pub fn generate_with_names_and_warnings(
    cookfile: &Cookfile,
    recipe_names: &BTreeSet<String>,
) -> (String, Vec<String>) {
    let warnings = warn_empty_output_refs(cookfile, recipe_names);
    let output = generate_with_names(cookfile, recipe_names);
    (output, warnings)
}

/// Detect references whose referent has an empty output list and return one
/// warning per offending (referrer, referent) pair.
///
/// "Empty output list" is approximated at codegen time as: no cook steps AND
/// no ingredients. A recipe with only ingredients still has a non-empty output
/// list per § 5.4.1 passthrough; a recipe whose ingredient globs resolve to
/// nothing at register time is still flagged by the runtime, not here.
fn warn_empty_output_refs(
    cookfile: &Cookfile,
    recipe_names: &BTreeSet<String>,
) -> Vec<String> {
    let empty: BTreeSet<String> = cookfile
        .recipes
        .iter()
        .filter(|r| {
            r.ingredients.is_empty()
                && !r.steps.iter().any(|s| matches!(s, Step::Cook { .. }))
        })
        .map(|r| r.name.clone())
        .collect();

    let mut warnings = Vec::new();
    for recipe in &cookfile.recipes {
        for dep_ref in extract_dep_refs(recipe, recipe_names) {
            if empty.contains(&dep_ref.recipe_name) {
                warnings.push(format!(
                    "recipe '{}' references '{}' which has empty output",
                    recipe.name, dep_ref.recipe_name
                ));
            }
        }
    }
    warnings
}

pub fn generate_with_names(cookfile: &Cookfile, recipe_names: &BTreeSet<String>) -> String {
    let mut out = String::from("-- Generated by Cook\n");

    // Emit module loading for use statements
    for use_stmt in &cookfile.uses {
        let lua_name = use_stmt.module_name.replace('-', "_");
        out.push_str(&format!(
            "local {} = cook.load_module(\"{}\")\n",
            lua_name,
            escape_lua_string(&use_stmt.module_name),
        ));
    }
    if !cookfile.uses.is_empty() {
        out.push('\n');
    }

    // Config-block dispatcher
    if !cookfile.config_blocks.is_empty() {
        out.push_str("function __cook_run_config_blocks(selected_name)\n");

        // Unnamed (base) block — always runs
        for block in &cookfile.config_blocks {
            if block.name.is_none() {
                for line in block.body.lines() {
                    out.push_str("    ");
                    out.push_str(line);
                    out.push('\n');
                }
            }
        }

        // Named blocks — run if selected_name matches
        let has_named = cookfile.config_blocks.iter().any(|b| b.name.is_some());
        if has_named {
            out.push_str("    if selected_name ~= nil then\n");
            for block in &cookfile.config_blocks {
                if let Some(name) = &block.name {
                    out.push_str(&format!(
                        "        if selected_name == \"{}\" then\n",
                        escape_lua_string(name)
                    ));
                    for line in block.body.lines() {
                        out.push_str("            ");
                        out.push_str(line);
                        out.push('\n');
                    }
                    out.push_str("        end\n");
                }
            }
            out.push_str("    end\n");
        }

        out.push_str("end\n\n");
    }

    for recipe in &cookfile.recipes {
        out.push_str(&format!(
            "cook.recipe(\"{}\", {}, function()\n",
            escape_lua_string(&recipe.name),
            generate_metadata(recipe)
        ));

        // Emit local ingredients variable when recipe has ingredients
        if !recipe.ingredients.is_empty() {
            let includes: Vec<String> = recipe
                .ingredients
                .iter()
                .map(|s| format!("\"{}\"", escape_lua_string(s)))
                .collect();
            let excludes: Vec<String> = recipe
                .excludes
                .iter()
                .map(|s| format!("\"{}\"", escape_lua_string(s)))
                .collect();
            out.push_str(&format!(
                "    local ingredients = cook.resolve_ingredients({{{}}}, {{{}}})\n",
                includes.join(", "),
                excludes.join(", "),
            ));
        }

        let mut prev_cook_index: Option<usize> = None;
        let mut cook_index: usize = 0;

        for step in &recipe.steps {
            match step {
                Step::Shell { command, line, interactive } => {
                    let wrapped = wrap_lua_string(command);
                    if *interactive {
                        out.push_str(&format!(
                            "    cook.add_unit({{command = {}, interactive = true, line = {}, cache = false}})\n",
                            wrapped, line
                        ));
                    } else {
                        out.push_str(&format!(
                            "    cook.add_unit({{command = {}, cache = false}})\n",
                            wrapped
                        ));
                    }
                }
                Step::Lua { code, .. } => {
                    out.push_str(&format!("    {}\n", code));
                }
                Step::LuaBlock { code, .. } => {
                    for code_line in code.lines() {
                        out.push_str(&format!("    {}\n", code_line));
                    }
                }
                Step::Cook {
                    step: cook_step,
                    line,
                } => {
                    cook_index += 1;
                    // Hoist output collection variable to recipe scope
                    // so subsequent step_groups can reference it
                    out.push_str(&format!("    local _cook_outputs_{} = {{}}\n", cook_index));
                    out.push_str("    cook.step_group(function()\n");
                    generate_cook_step(
                        &mut out,
                        cook_step,
                        *line,
                        cook_index,
                        prev_cook_index,
                        &recipe.ingredients,
                        recipe_names,
                    );
                    out.push_str("    end)\n");
                    prev_cook_index = Some(cook_index);
                }
                Step::Plate {
                    step: plate_step,
                    line,
                } => {
                    out.push_str("    cook.step_group(function()\n");
                    generate_plate_step(&mut out, plate_step, *line, prev_cook_index, recipe_names);
                    out.push_str("    end)\n");
                }
                Step::Test {
                    step: test_step_val,
                    line,
                } => {
                    out.push_str("    cook.step_group(function()\n");
                    test_step::generate_test_step(&mut out, test_step_val, *line, prev_cook_index, recipe_names);
                    out.push_str("    end)\n");
                }
            }
        }

        out.push_str("end)\n\n");
    }

    out
}

fn generate_metadata(recipe: &Recipe) -> String {
    let mut fields = Vec::new();
    if !recipe.ingredients.is_empty() {
        let items: Vec<String> = recipe
            .ingredients
            .iter()
            .map(|s| format!("\"{}\"", escape_lua_string(s)))
            .collect();
        fields.push(format!("ingredients = {{{}}}", items.join(", ")));
    }
    if !recipe.excludes.is_empty() {
        let items: Vec<String> = recipe
            .excludes
            .iter()
            .map(|s| format!("\"{}\"", escape_lua_string(s)))
            .collect();
        fields.push(format!("excludes = {{{}}}", items.join(", ")));
    }
    if !recipe.deps.is_empty() {
        let items: Vec<String> = recipe
            .deps
            .iter()
            .map(|s| format!("\"{}\"", escape_lua_string(s)))
            .collect();
        fields.push(format!("requires = {{{}}}", items.join(", ")));
    }
    if fields.is_empty() {
        "{}".to_string()
    } else {
        format!("{{{}}}", fields.join(", "))
    }
}
