name: smoke
on:
  push:
    paths:
      - .gitea/workflows/smoke.yml
jobs:
  hello:
    runs-on: native
    steps:
      - run: |
          echo "host: $(uname -a)"
          which git && git --version
          echo "PWD: $(pwd)"