#!/usr/bin/env bash
# Assert that the tracked src/ matches what this tree's grammar.js generates —
# WITHOUT regenerating into the tracked tree.
#
# The previous form ran `tree-sitter generate` in place and then diffed. That
# made a *test* mutate tracked source on every run, and it turned a CLI
# mismatch into a self-inflicted wound: a developer whose PATH resolved a
# different tree-sitter had src/ rewritten with that CLI's bytes, and the check
# then correctly reported the drift it had just caused. The dirty tree outlived
# the run and surfaced later as an unexplained `cook release` failure. Twice.
#
# Generation happens in a scratch directory instead; the tracked tree is only
# ever read. Run from tree-sitter-cook/ (the member root).
set -euo pipefail

# Generated by `tree-sitter generate`. scanner.c is hand-written and is an
# INPUT here, not an output.
GENERATED=(
	src/parser.c
	src/node-types.json
	src/grammar.json
	src/tree_sitter/alloc.h
	src/tree_sitter/array.h
	src/tree_sitter/parser.h
)

pinned=$(sed -n 's/.*"tree-sitter-cli": "[^0-9]*\([0-9.]*\)".*/\1/p' package.json)
actual=$(tree-sitter --version 2>/dev/null | sed -n 's/^tree-sitter \([0-9.]*\).*/\1/p')

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

cp grammar.js package.json tree-sitter.json "$tmp/"
mkdir -p "$tmp/src"
cp src/scanner.c "$tmp/src/"

( cd "$tmp" && tree-sitter generate >/dev/null )

differing=()
for f in "${GENERATED[@]}"; do
	if [ ! -f "$tmp/$f" ]; then
		echo "check-generated: $f was not produced by 'tree-sitter generate'" >&2
		differing+=("$f")
		continue
	fi
	if ! diff -q "$f" "$tmp/$f" >/dev/null 2>&1; then
		differing+=("$f")
	fi
done

if [ "${#differing[@]}" -ne 0 ]; then
	# Generated output is not stable across CLI versions (bd4fe6b0), so the
	# commonest cause of this failure is not a stale commit at all — it is the
	# wrong CLI. Lead with that, and suppress the per-file diffs: when the CLI
	# differs, every generated file differs, and six 40-line hunks bury the one
	# line that tells the reader what to do.
	if [ -n "$pinned" ] && [ -n "$actual" ] && [ "$pinned" != "$actual" ]; then
		echo "check-generated: your tree-sitter is $actual; this repo pins $pinned." >&2
		echo >&2
		echo "  Generated output differs between CLI versions, so that is almost" >&2
		echo "  certainly the whole story — ${#differing[@]} generated file(s) differ." >&2
		echo "  src/ has NOT been modified. Re-run with the pinned CLI:" >&2
		echo >&2
		echo "    PATH=\"\$PWD/tree-sitter-cook/node_modules/.bin:\$PATH\" cook ts.check-generated" >&2
		exit 1
	fi

	# Same CLI, real drift: the commit is stale. Show what moved.
	echo "check-generated: src/ does not match what grammar.js generates" >&2
	for f in "${differing[@]}"; do
		echo >&2
		echo "  --- $f" >&2
		diff -u "$f" "$tmp/$f" | head -30 >&2
	done
	echo >&2
	echo "check-generated: run 'cook ts.generate' and commit the result" >&2
	exit 1
fi

echo "check-generated: src/ matches grammar.js (tree-sitter $actual)"
